name: Update Models JSON (Daily)

on:
  schedule:
    - cron: "17 2 * * *"   # يوميًا 02:17 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run updater
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scripts/update_models.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "actions-bot"
            git config user.email "actions@users.noreply.github.com"
            git add models.json
            git commit -m "chore: daily models.json refresh [skip ci]"
            git push
          else
            echo "No changes."
          fi
